name: Python code checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with unittest
      run: |
        python -m unittest discover .

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install coverage
      run: |
        python -m pip install coverage httpie

    - name: Run coverage
      run: |
        python -m coverage run -m unittest discover .
        coverage report -m
        coverage json
        jq '.totals.percent_covered' coverage.json > coverage.txt
        http post https://delta-v.club/delta/b6553421-c107-4e0b-97a2-a8133991a936/track value=$(cat coverage.txt) --ignore-stdin

  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install bandit
        run: |
          python -m pip install bandit

      - name: Run bandit scan
        run: |
          bandit -r .

  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install black
        run: |
          python -m pip install black

      - name: Run black
        run: |
          black --check .

  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install ruff
      run: |
        python -m pip install ruff

    - name: Run ruff
      run: |
        ruff .
